apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: simple-web-app-mvc-dotnet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web-app-mvc-dotnet
  template:
    metadata:
      labels:
        app: simple-web-app-mvc-dotnet
    spec:
      containers:
      - name: simple-web-app-mvc-dotnet
        image: thicksy/simple-web-app-mvc-dotnet:latest
        ports:
        - containerPort: 80
