apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: dotnet-banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-banking-app
  template:
    metadata:
      labels:
        app: dotnet-banking-app
    spec:
      containers:
      - name: dotnet-banking-app
        image: thicksy/simple-web-app-mvc-dotnet:latest
        ports:
        - containerPort: 80
