apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: staging  # Namespace where the .NET app is deployed
  name: jenkins-deployment-role
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["deployments", "replicasets", "pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
